version: 2.1
general:
  branches:
    only:
      - main
jobs:
  build:
    docker:
      - image: cimg/python:3.8
     

    working_directory: ~/tip_calculator
    
    steps:
      #1 Obtain repo from github 
      - checkout
      #2 Create virtual environment and install dependencies -
      - run: 
          name: Triggering the build
          command: |
           python3 -m pip install --upgrade pip
           python3 -m venv venv
           . venv/bin/activate
           venv/bin/pip3 install -U pip setuptools virtualenv  
           venv/bin/pip3 install -r requirements.txt
           venv/bin/pip3 install -U wheel
      #3 Run coding coversion software plus tester - 
      - run: 
          name: Deploy, Run & Clean-up
          command: | 
           . venv/bin/activate
           venv/bin/python3 ~/tip_calculator/tip_calculator.py 200 20
           mkdir ~/DEPLOY-$(date '+%Y%m%d')
           deactivate
           rm -rf ~/tip_calculator/__pycache__
           rm -rf ~/tip_calculator/venv/__pycache__
           rm -rf ~/tip_calculator/venv
           cp -r ~/tip_calculator ~/DEPLOY-$(date '+%Y%m%d')
           aws s3 cp ~/DEPLOY-$(date '+%Y%m%d') s3://uchicago-module5-assignment/DEPLOY-$(date '+%Y%m%d') --recursive
           rm -rf ~/DEPLOY-$(date '+%Y%m%d')
