version: 2.1
general:
  branches:
    only:
      - main
jobs:
  build:
    docker:
      - image: cimg/python:3.8
     

    working_directory: ~/tip_calculator
    
    steps:
      #1 Obtain repo from github 
      - checkout
      #2 Create virtual environment and install dependencies -
      - run: 
          name: Triggering the build
          command: |
           python3 -m pip install --upgrade pip
           python3 -m venv venv
           . venv/bin/activate
           venv/bin/pip3 install -U pip setuptools virtualenv  
           venv/bin/pip3 install -r requirements.txt
           venv/bin/pip3 install pytest pytest-cov
           venv/bin/pip3 install -U wheel 
           venv/bin/pip3 install awscli
      #2 Perform the automated tests with pytest 
      - run: 
          name: Run tests 
          command: | 
           . venv/bin/activate
           venv/bin/pytest
      - store_test_results: 
           path: test-results 
      - store_artifacts: 
           path: test-results        
          
      #3 Run coding coversion software plus tester - 
      - run: 
          name: Deploy, Run & Clean-up
          command: | 
           . venv/bin/activate
           venv/bin/python3 ~/tip_calculator/tip_calculator.py 200 20
           mkdir ~/DEPLOY-$(date '+%Y%m%d')
           cp -r ~/tip_calculator/* ~/DEPLOY-$(date '+%Y%m%d')
           echo -e "\nUploading Deployment artifacts to AWS S3..\n"
           venv/bin/aws s3 cp ~/DEPLOY-$(date '+%Y%m%d') s3://uchicago-module5-assignment/DEPLOY-$(date '+%Y%m%d') --recursive --exclude "venv/*" --exclude "__pycache__/*"
           venv/bin/aws s3 cp test-results s3://uchicago-module5-assignment/DEPLOY-$(date '+%Y%m%d')/test-results --recursive --exclude "venv/*" --exclude "__pycache__/*"
           deactivate
           rm -rf ~/tip_calculator/__pycache__
           rm -rf ~/tip_calculator/venv/__pycache__
           rm -rf ~/tip_calculator/venv
           rm -rf ~/DEPLOY-$(date '+%Y%m%d')
